In [1]:
import torch

#### - The `rand(3)` means only positive randoms while the `randn(3)` includes negative randoms too

In [23]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.3389,  0.7706,  1.0508], requires_grad=True)


In [24]:
# For addition <AddBackward>
z1 = x + 2
print(z1)

tensor([1.6611, 2.7706, 3.0508], grad_fn=<AddBackward0>)


#### - A graph is maintained when `requires_grad=True` just like the following

<img src="images/computational_graph.png" height="30%" width="30%">
<ul>

In [25]:
# For multiplication <MulBackward>
z2 = x * x * 2
print(z2)

tensor([0.2297, 1.1875, 2.2085], grad_fn=<MulBackward0>)


In [26]:
# For mean <MeanBackward>
z3 = z2.mean()
print(z3)

tensor(1.2086, grad_fn=<MeanBackward0>)


In [28]:
# To calculate gradient
z3.backward() #dz1/dx
print(x.grad)

tensor([-0.4518,  1.0274,  1.4011])


#### - A short gradient calculation
<ul>
    <li>Forward Pass (Black)</li>
    <li>Backward Pass (Red)</li>
</ul>

<img src="images/simple_neuralnet.png">

In [78]:
# Define feature, label and weight
x = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(4.0)

In [79]:
# The forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2
print("y_hat: ", y_hat.item())
print("loss: ", loss.item())

y_hat:  2.0
loss:  4.0


In [80]:
# The backward pass and gradient computation (main with local)
loss.backward()

In [81]:
# The final weight derivative after gradient calculation
print("dL/dw: ",w.grad.item())

dL/dw:  -8.0


In [82]:
# Update the weight with the learning rate
w = w - 0.01 * w.grad
print("New weight" ,w.item())

New weight 1.0800000429153442
