# Introduction to PyTorch

## 1 - Beginner's Level Fundamentals

#### - Basic import and `empty(rows, cols)`

In [1]:
# Importing PyTorch
import torch

In [2]:
# Create a tensor of an empty item - value not initialized
x = torch.empty(1)
print(x)

# Create a tensor of three empty items - values not initialized
x = torch.empty(3)
print(x)

tensor([2.8023e-15])
tensor([4.5297e-14, 4.5848e-41, 4.6380e-14])


In [3]:
# Create a 2D-tensor of empty items - values not initialized
x = torch.empty(2,3)
print(x)

# Create a 3D-tensor of empty items - values not initialized
x = torch.empty(2,2,3)
print(x)

tensor([[-1.0842e-19,  4.1382e-02,  0.0000e+00],
        [ 1.7160e-05,  0.0000e+00,  4.1531e-02]])
tensor([[[3.5733e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


#### - The `torch.rand(rows, cols)` function

In [4]:
# Create a tensor of random items
x = torch.rand(2)
print(x)

# Create a 2D-tensor of random items
x = torch.rand(3,3)
print(x)

tensor([0.8437, 0.5846])
tensor([[0.8003, 0.3046, 0.8499],
        [0.6699, 0.6184, 0.3781],
        [0.3774, 0.5651, 0.9609]])


#### - The `zeros(rows, cols)` and `ones(rows, cols)` functions

In [5]:
# Create a tensor of zeros
x = torch.zeros(3, 3)
print(x)

# and, ones
x = torch.ones(3, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# Data type of the tensor
x = torch.ones(2,2, dtype=torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


#### - Data types, the `dtype` used in PyTorch, `size()` function and creating tensor from a list `tensor( [list] )`

In [7]:
# Tensor datatype
print(x.dtype)

# Tensor size
print(x.size())

torch.float16
torch.Size([2, 2])


In [8]:
# Create a custom tensor from a list[]
x = torch.tensor([21.52, 10.33, 41,11])
print(x)

tensor([21.5200, 10.3300, 41.0000, 11.0000])


#### - Arithmetic Operations on PyTorch Tensors

In [9]:
# Operations on tensors
x = torch.rand(2,2)
y = torch.rand(2,2)
print("Tensor#1\n",x)
print("Tensor#2\n",y)

Tensor#1
 tensor([[0.2810, 0.6678],
        [0.9238, 0.8507]])
Tensor#2
 tensor([[0.8926, 0.3419],
        [0.0118, 0.2390]])


In [10]:
# Element wise addition
z = x+y
print("Resultant Tensor\n",z)

Resultant Tensor
 tensor([[1.1737, 1.0096],
        [0.9356, 1.0896]])


In [11]:
# Also element wise addition
z = torch.add(x, y)
print("Resultant Tensor\n",z)

Resultant Tensor
 tensor([[1.1737, 1.0096],
        [0.9356, 1.0896]])


In [12]:
# Also element wise addition but storing in y
y.add_(x)
print("Resultant Tensor\n",y)

Resultant Tensor
 tensor([[1.1737, 1.0096],
        [0.9356, 1.0896]])


In [13]:
# Arithmatic Operation

# Addition
#z = x+y
#z = torch.add(x, y)
#y.add_(x)

# Subtraction
#z = x-y
#z = torch.sub(x, y)
#y.sub_(x)

# Multiplication
#z = x*y
#z = torch.mul(x, y)
#y.mul_(x)

# Division
#z = x/y
#z = torch.div(x, y)
#y.div_(x)

#### -  Indexing `x[0]`, Slicing `x[:2]` or `x[2:]` and Fancy Indexing `x[0, [0,1,2]]` or `x[[0,1,2], 0]`

In [14]:
x = torch.tensor([22,44,55,66,88])
print(x)

tensor([22, 44, 55, 66, 88])


In [15]:
# First element
print("First element", x[0], end='\n\n')

# Last element
print("Last element", x[-1], end='\n\n')

# First two elements
print("First two elements", x[:2], end='\n\n')

# Elements after second item
print("Elements after second item", x[2:], end='\n\n')

# Last two elements
print("Last two elements", x[-2:], end='\n\n')

First element tensor(22)

Last element tensor(88)

First two elements tensor([22, 44])

Elements after second item tensor([55, 66, 88])

Last two elements tensor([66, 88])



In [16]:
x = [
    [1,   2,  3,  4,  5],
    [6,   7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
x = torch.tensor(x)
print(x)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])


In [17]:
# First row
print("First row", x[0], end='\n\n')

# Last row
print("Last row", x[-1], end='\n\n')

# First column
print("First column", x[:, 0], end='\n\n')

# Last column
print("Last column", x[:, -1], end='\n\n')

First row tensor([1, 2, 3, 4, 5])

Last row tensor([21, 22, 23, 24, 25])

First column tensor([ 1,  6, 11, 16, 21])

Last column tensor([ 5, 10, 15, 20, 25])



In [18]:
# First two elements at first row
print("First two elements at first row", x[0, [0,1]], end='\n\n')

# Last two elements at first row
print("Last two elements at first row", x[0, [-2,-1]], end='\n\n')

# First two elements at last row
print("First two elements at last row", x[-1, [0,1]], end='\n\n')

# Last two elements at last row
print("Last two elements at last row", x[-1, [-2,-1]], end='\n\n')

First two elements at first row tensor([1, 2])

Last two elements at first row tensor([4, 5])

First two elements at last row tensor([21, 22])

Last two elements at last row tensor([24, 25])



In [19]:
x = [
    [1,   2,  3,  4,  5],
    [6,   7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
]
x = torch.tensor(x)
print(x)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])


In [20]:
# First two elements at first column
print("First two elements at first column", x[[0,1], 0], end='\n\n')

# Last two elements at first column
print("Last two elements at first column", x[[-2,-1], 0], end='\n\n')

# First two elements at last column
print("First two elements at last column", x[[0,1], -1], end='\n\n')

# Last two elements at last column
print("Last two elements at last column", x[[-2,-1], -1], end='\n\n')

First two elements at first column tensor([1, 6])

Last two elements at first column tensor([16, 21])

First two elements at last column tensor([ 5, 10])

Last two elements at last column tensor([20, 25])



In [21]:
# First two elements in first two rows
print("First two elements in first two rows\n", x[:2,[0,1]], end='\n\n')

# Last two elements in last two rows
print("Last two elements in last two rows\n", x[[0,1], -2:], end='\n\n')

# First two elements in first two columns
print("First two elements in first two columns\n", x[:2,:2], end='\n\n')

# Last two elements in last two columns
print("Last two elements in last two columns\n", x[-2:,-2:], end='\n\n')

First two elements in first two rows
 tensor([[1, 2],
        [6, 7]])

Last two elements in last two rows
 tensor([[ 4,  5],
        [ 9, 10]])

First two elements in first two columns
 tensor([[1, 2],
        [6, 7]])

Last two elements in last two columns
 tensor([[19, 20],
        [24, 25]])



#### - The `item()` function

In [22]:
# Need to print a python scalar from the tensor
print("A tensor item: ", x[0,-1])
print("A scalar item: ", x[0,-1].item())

A tensor item:  tensor(5)
A scalar item:  5


## 2 - Intermediate Level

#### - The `reshape(rows, cols)` of numpy is `view(rows, cols)` in PyTorch

#### - Telling `rows` and `cols`

In [25]:
# To a higher dimension
x = torch.tensor([1,2,3,4,5,6])

# 2D dimensional tensors - telling rows and cols
x1 = x.view(2,3)
x2 = x.view(3,2)

# Displayed
print("2D - x1\n", x1)
print("2D - x2\n", x2)

x1
 tensor([[1, 2, 3],
        [4, 5, 6]])
x2
 tensor([[1, 2],
        [3, 4],
        [5, 6]])


#### - Just telling one `rows` or `cols` and keeping the other as `-1`

In [50]:
# To a higher dimension
x = torch.tensor([1,2,3,4,5,6,7,8,9,10,11,12])
print("1D - x\n", x, end='\n\n')

# 2D dimensional tensors - telling either rows or cols
x1 = x.view(4,-1)
x2 = x.view(-1,6)

# Displayed
print("2D - x1\n", x1)
print("2D - x2\n", x2)

1D - x
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

2D - x1
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
2D - x2
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


In [45]:
# A 3D tensor - to lower dimensions
x = torch.rand(3,3,2)
print("3D - x\n", x)

3D - x
 tensor([[[0.2420, 0.2802],
         [0.0695, 0.9632],
         [0.8461, 0.3509]],

        [[0.0309, 0.6693],
         [0.4334, 0.4676],
         [0.7783, 0.8743]],

        [[0.2934, 0.1100],
         [0.8186, 0.3515],
         [0.0674, 0.8360]]])


In [46]:
# Down to 2D dimensional tensors - telling either rows or cols
x1 = x.view(9,-1)
x2 = x.view(-1,6)

# Displayed
print("2D - x1\n", x1)
print("2D - x2\n", x2)

2D - x1
 tensor([[0.2420, 0.2802],
        [0.0695, 0.9632],
        [0.8461, 0.3509],
        [0.0309, 0.6693],
        [0.4334, 0.4676],
        [0.7783, 0.8743],
        [0.2934, 0.1100],
        [0.8186, 0.3515],
        [0.0674, 0.8360]])
2D - x2
 tensor([[0.2420, 0.2802, 0.0695, 0.9632, 0.8461, 0.3509],
        [0.0309, 0.6693, 0.4334, 0.4676, 0.7783, 0.8743],
        [0.2934, 0.1100, 0.8186, 0.3515, 0.0674, 0.8360]])


In [47]:
x3 = x.view(-1)
print("1D - x3\n", x3)

1D - x3
 tensor([0.2420, 0.2802, 0.0695, 0.9632, 0.8461, 0.3509, 0.0309, 0.6693, 0.4334,
        0.4676, 0.7783, 0.8743, 0.2934, 0.1100, 0.8186, 0.3515, 0.0674, 0.8360])


#### - Typecasting with `NumPy` and some `cuda` operations

In [55]:
import numpy as np

In [64]:
a = torch.ones(5)
print(a,"\n",type(a))

b = a.numpy()
print(b,"\n",type(b))

tensor([1., 1., 1., 1., 1.]) 
 <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] 
 <class 'numpy.ndarray'>


In [65]:
a.add_(1)
print(a)

# Because both a and b points to the same location
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [73]:
a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [74]:
# Both will be changed again
a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [77]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    z.to('cpu')
else:
    print("Not available")

Not available


#### - For optimizing a variable or a vector or a matrix, we do `requires_grad=True` when creating it - `False` by default

In [78]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
