In [1]:
import numpy as np

In [2]:
#Create a ramge
v = np.arange(0, 10, 2) #start, stop, step
v

array([0, 2, 4, 6, 8])

In [3]:
#Create a range with float
v = np.arange(0, 10, 0.5) #start, stop, step
v # 0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [4]:
# Using linspace, both end points ARE INCLUDED
v = np.linspace(0, 10, 2) #start, stop, number of points
v # 2 points, 0 and 10

array([ 0., 10.])

In [5]:
# Uniform random numbers in [0,1]
from numpy import random
v = random.rand(3,3) #3x3 matrix
v #uniform random numbers in [0,1]


array([[0.38099429, 0.48378482, 0.90394739],
       [0.08384209, 0.24550615, 0.23779919],
       [0.11484193, 0.62706604, 0.09131914]])

In [6]:
# Uniform random numbers in [2,5]
v = random.rand(5,5) * 3 + 2
v  # 5x5 matrix with random numbers in [2,5]

array([[2.47491051, 4.61260836, 2.90165959, 2.36817394, 4.8493014 ],
       [3.90051746, 2.5647063 , 2.5684187 , 3.54547369, 4.21094817],
       [2.15268218, 3.05943193, 4.47491497, 4.65789202, 4.41967573],
       [2.27424491, 2.35688534, 2.33841733, 4.27909557, 4.91927205],
       [2.25086103, 3.58075383, 4.95140376, 4.14419751, 4.82333301]])

In [7]:
# Diagonal with offset from the main diagonal
M = np.diag([1,2,3,4,5,6], k=-1) # k = 0 is the main diagonal
M # k = 1 is the first diagonal above the main diagonal, k = -1 is the first diagonal below the main diagonal

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0]])

In [8]:
# Matrix creation by array input
M = np.array([[1,21,18],[63,5,6],[7,8,9]]) # 3x3 matrix

In [9]:
# main diagonals
print("Main Diagonal Elements:\n", np.diag(M)) # main diagonals

Main Diagonal Elements:
 [1 5 9]


In [10]:
# Flipped main diagonals
print("Right Diagonal Elements:\n", np.diag(np.fliplr(M))) #flip left to right
print("\nRight Diagonal Elements:\n", np.diag(np.flipud(M),-1)) #flip up to down
print("\nRight Diagonal Elements:\n", np.diag(np.flipud(M),+1)) #flip up to down

Right Diagonal Elements:
 [18  5  7]

Right Diagonal Elements:
 [63 21]

Right Diagonal Elements:
 [8 6]


In [11]:
# Zeroes and Ones
# Zeroes
M = np.zeros((6,3)) # 6 rows, 3 columns
M # 6x3 matrix with all zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# Ones
M = np.ones((8,4)) # 8 rows, 4 columns
M # 8x4 matrix with all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# Loading a .csv file using numpy
from numpy import genfromtxt # import genfromtxt
my_data = genfromtxt('data.csv', delimiter=',') # load data
my_data # 2D array

FileNotFoundError: data.csv not found.

In [ ]:
# Shape of the array
my_data.shape # (100, 3) 100 rows, 3 columns

In [ ]:
# To plot the data, we use matplotlib
from matplotlib import pyplot as plt

In [ ]:
# Plot the data
X = [0, 7, 4] # x coordinates
Y = [0, 3, 4] # y coordinates

In [ ]:
# Plot the data
plt.plot(X, Y) # plot the data

In [ ]:
# Plot from Diabetes dataset
data = genfromtxt('diabetes.csv', delimiter=',') # load data
data # 2D array

In [ ]:
# Generate a matrix
M = random.rand(5,5) # 5x5 matrix

In [ ]:
# Save the matrix
np.savetxt('my_matrix.csv', M, delimiter=',') # save the matrix

In [ ]:
# Load the matrix
!cat my_matrix.csv # print the matrix

In [ ]:
# Save the matrix
M = np.savetxt('my_matrix.csv', M, fmt='%.2f') # save the matrix
!cat random_matrix.csv # print the matrix

In [ ]:
# Numpy's native format
M = random.rand(10,5) # 10x5 matrix
np.save('my_matrix.npy', M) # save the matrix

In [ ]:
# Load the matrix
np.load('my_matrix.npy') # load the matrix

In [ ]:
# Numpy's native format
M.itemsize # bytes per element

In [ ]:
# Numpy's native format
M.nbytes # total bytes

In [ ]:
# Numpy's native format
M.ndim # number of dimensions

In [ ]:
# M is a matrix, or a 2-dimensional array, taking two indices
M[1,1] # second row, second column
M[1][1] # second row, second column

In [ ]:
# Also works for rows and columns
M[1,:] = 0 # second row, all columns
M[:,1] = 0 # all rows, second column

In [ ]:
# M is a matrix, or a 2-dimensional array, taking two indices
v[::] # lower bound, upper bound, step all take default values

In [ ]:
# Create a vector
v = np.array([1,2,3,4,5,6,7,8,9,10]) # 1D array
v[::2] # 1,3,5,7,9

In [ ]:
exm =[i for i in range[10]] # 1D array
exm # 1,2,3,4,5,6,7,8,9,10

In [ ]:
M = np.array(
    [
        [m for n in range(5)] for m in range(5) # 5x5 matrix
    ]
)
M # 5x5 matrix

In [ ]:
# Fancy indexing is the name for when an array or list is used in-place of an index
row_indices = [0, -1]
M[row_indices] # first and last row

In [ ]:
col_indices = [0, -1] # remember, index -1 means the last element
M[:, col_indices] # first and last column

In [ ]:
# Matric Algebra
A = np.array([[1,2],[3,4]]) # 2x2 matrix

In [ ]:
np.dot(A,A) # matrix multiplication

In [ ]:
np.dot(A,A.T) # matrix multiplication

In [ ]:
# Inner Product
v.T = v # transpose of v

In [ ]:
# Outer Product
v = v.T # transpose of v

In [ ]:
# Determinant
D = np.linalg.det(A) # determinant of A
D

In [ ]:
# Inverse
I = np.linalg.inv(A) # inverse of A
I

In [ ]:
# Global Maximum
M.globalmax() # global maximum of M

In [ ]:
# Naximum of each column
M.max(axis=0) # maximum of each column

In [ ]:
# Maximum of each row
M.max(axis=1) # maximum of each row

In [ ]:
# Minimum of each column
M.min(axis=0) # minimum of each column

In [ ]:
# Minimum of each row
M.min(axis=1) # minimum of each row

In [ ]:
v1 = np.arange(0, 10000)
v1

In [ ]:
%%time
for i in range(v1.shape[0]):
    v1[i] = 2 * v1[i]

In [ ]:
# Scalar Array Operations
v1 + 2 # add 2 to each element

In [ ]:
print(v1 *2) # multiply by 2
v1 + 2 # add 2

In [ ]:
# Reshaping, Resizing and Stacking Arrays
v = np.array([1,2,3,4,5,6,7,8,9,10]) # 1D array
v

In [ ]:
# Reshape
v.reshape(2,5) # 2x5 matrix

In [ ]:
v.reshape(5,2) # 5x2 matrix

In [ ]:
# Resize
v.resize(2,5) # 2x5 matrix
v

In [ ]:
v.resize(5,2) # 5x2 matrix

In [ ]:
# Stacking
v1 = np.array([1,2,3,4,5,6,7,8,9,10]) # 1D array
v2 = np.array([11,12,13,14,15,16,17,18,19,20]) # 1D array

In [ ]:
# Stack vertically
np.vstack([v1, v2]) # 2x10 matrix

In [ ]:
# Stack horizontally
np.hstack([v1, v2]) # 1x20 matrix