### Numpy Exercise
In this exercise, we will be working with a dataset with the information of baseball players. Here is the code to read the dataset and convert it into lists.

#### Advanced Operations

1. Construct an array from the list: [1,2,3]
2. Cast it into floats
3. Create an array of int ranging from 0-10 
4. Create an array containing 7 evenly spaced numbers between 0 and 23
5. Create an array with shape (2,5,1,5,2,1) containing only the number 5
6. Eliminate all length-1 dimensions. See the function squeeze.
7. Reshape the resulting array from shape (2,5,3,2) to only 2D
8. Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn
from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.
9. Do the same but not on all elements but only on the 2nd dimension. 
10. Transform the array such that it is only 1d. See the function Flatten or ravel
11. Remove all values smaller 15 and larger 26.
12. Clip all values smaller 15 and larger 26 to NaN. See the function Clip
13. Calculate the sum of the resulting array. It should not be NaN!.
14. Convert the NaN’s to 0.0. See Where
15. Save the array and load it again.

In [63]:
from numpy import *
from matplotlib.pyplot import *
import numpy as np
import matplotlib.pyplot as plt

In [64]:
# Construct an array from the list: [1,2,3]
A = np.array([1,2,3])
A

array([1, 2, 3])

In [65]:
# Cast the array into float
A = A.astype(float)
A

array([1., 2., 3.])

In [66]:
# Create an array of int ranging from 0-10
B = np.arange(0,10)
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# Create an array containing 7 evenly spaced numbers between 0 and 23
C = np.linspace(0,23,7)
C

array([ 0.        ,  3.83333333,  7.66666667, 11.5       , 15.33333333,
       19.16666667, 23.        ])

In [68]:
# Create an array with shape (2,5,1,5,2,1) containing only the number 5
D = np.full((2,5,1,5,2,1),5)
D

array([[[[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]]]],



        [[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]]]],



        [[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]]]],



        [[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]]]],



        [[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]]]]],




       [[[[[5],
           [5]],

          [[5],
           [5]],

          [[5],
           [5]],

          [[5],
          

In [69]:
# Eliminate all length-1 dimensions. See the function squeeze.
E = np.squeeze(D)
E

array([[[[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]]],


       [[[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]],

        [[5, 5],
         [5, 5],
         [5, 5],
         [5, 5],
         [5, 5]]]])

In [70]:
# Reshape the resulting array to from (2,5,3,2) only 2D
E = np.reshape(D,(2,50))
E

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5]])

In [71]:
# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.
F = np.random.normal(21,4.5,(3,3,12,3))
F


array([[[[20.25224681, 17.14864359, 18.7006816 ],
         [25.01813392, 15.88405212, 20.15422097],
         [17.01509256, 14.12586645, 15.28477647],
         [15.59315939, 24.64507937, 21.03019422],
         [20.24803065, 23.76411829, 13.4935379 ],
         [22.17925905, 17.58928019, 22.8774333 ],
         [22.43308251, 19.89480215, 23.13775691],
         [16.78087843, 17.85848556, 24.7671299 ],
         [21.33366145, 22.65645739, 18.8449249 ],
         [20.38290666, 18.19708606, 15.19766568],
         [22.43241278, 22.55745785, 21.66605272],
         [15.40301505, 20.42405656, 24.68721784]],

        [[17.81856422, 25.78879738, 18.15884637],
         [12.04596336, 23.88436024, 21.01404093],
         [25.7924046 , 21.57423508, 15.65517152],
         [17.63178114, 18.50624211, 18.86069672],
         [24.19083211, 23.23296816, 18.39084823],
         [27.61382148, 12.74150143, 17.01881564],
         [13.35138333, 18.18374351, 19.32357243],
         [ 6.85470038, 16.72444971, 12.4654614 ]

In [72]:
# Do the same but not on all elements but only on the 2nd dimension.
F = np.mean(F,axis=1)
F

array([[[17.72982743, 20.05980226, 16.42999066],
        [21.01803755, 18.82612844, 22.14219606],
        [19.68051491, 17.64659465, 19.6977848 ],
        [17.33029782, 22.82290769, 20.06148312],
        [20.33932844, 24.53783581, 18.50575918],
        [21.63059819, 15.25417769, 18.28135011],
        [18.24840399, 21.66296674, 20.6301477 ],
        [15.23398318, 18.17828143, 22.55872332],
        [22.36925908, 20.38185364, 20.45300726],
        [18.5270889 , 18.02904468, 18.61857718],
        [26.06372077, 22.39908703, 22.73512138],
        [18.45495846, 20.86011107, 21.13864565]],

       [[21.2939232 , 20.13537846, 20.84490059],
        [15.72380883, 19.79581049, 23.60188866],
        [20.84618577, 19.43508051, 22.61771167],
        [21.34949511, 19.13389248, 20.51630189],
        [23.10491831, 21.64737894, 20.85190326],
        [20.56079026, 26.22887994, 21.6538792 ],
        [23.90875417, 19.97458822, 24.58920405],
        [23.23909181, 20.59445006, 25.80633235],
        [19.298786

In [73]:
# Transform the array such that it is only 1d. See the function Flatten or ravel
F = np.ravel(F)
F

array([17.72982743, 20.05980226, 16.42999066, 21.01803755, 18.82612844,
       22.14219606, 19.68051491, 17.64659465, 19.6977848 , 17.33029782,
       22.82290769, 20.06148312, 20.33932844, 24.53783581, 18.50575918,
       21.63059819, 15.25417769, 18.28135011, 18.24840399, 21.66296674,
       20.6301477 , 15.23398318, 18.17828143, 22.55872332, 22.36925908,
       20.38185364, 20.45300726, 18.5270889 , 18.02904468, 18.61857718,
       26.06372077, 22.39908703, 22.73512138, 18.45495846, 20.86011107,
       21.13864565, 21.2939232 , 20.13537846, 20.84490059, 15.72380883,
       19.79581049, 23.60188866, 20.84618577, 19.43508051, 22.61771167,
       21.34949511, 19.13389248, 20.51630189, 23.10491831, 21.64737894,
       20.85190326, 20.56079026, 26.22887994, 21.6538792 , 23.90875417,
       19.97458822, 24.58920405, 23.23909181, 20.59445006, 25.80633235,
       19.29878605, 22.16632369, 21.30995479, 21.27960767, 27.67989484,
       27.50623098, 24.41344295, 18.8706902 , 22.40349816, 17.27

In [74]:
# Remove all values smaller 15 and larger 26.
G = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30])
G = G[(G>15) & (G<26)]
G

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [75]:
# Calculate the sum of the resulting array. It should not be NaN!.
G = np.sum(G)
G

205

In [76]:
# Convert the NaN’s to 0.0. See Where
G = np.where(np.isnan(G),0,G)
G

array(205)

In [77]:
# Save the array and load it again.
np.save('G.npy',G)
G = np.load('G.npy')
G

array(205)